# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Marie B Cusick"
title: "Content Creator & Impact Storyteller"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Content Creator & Impact Storyteller"

# Keywords tag for SEO (separated by comma)
keywords: ""


# The subpath of your site, e.g. /blog, for generating urls
baseurl:
# baseurl: https://beingeorge.com/lancer-jekyll

navigation:
- text: Home
  url: /#home
- text: about
  url: /#about
- text: services
  url: /#services
- text: Works
  url: /#portfolio
- text: Blog
  url: /#blog
- text: Contact
  url: /#contact

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://marie-cusick.com"

# Social image
social_image: "about.jpg"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Marie B Cusick"

# Social links in the site footer
twitter_username: "cusick_marie"
linkedin_username: "mariebcusick"
facebook_username:
googleplus_username:
pinterest_username:
